---
# tasks file for salt-minions

- name: import gpg
  command: rpm --import https://repo.saltproject.io/salt/py3/redhat/8/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub

# - name: install salt repo
#   command: curl -fsSL https://repo.saltproject.io/salt/py3/redhat/8/x86_64/latest.repo | tee /etc/yum.repos.d/salt.repo

- name: salt repo
  get_url:
    url:  https://repo.saltproject.io/salt/py3/redhat/8/x86_64/latest.repo
    dest:  /etc/yum.repos.d/salt.repo

- name: install salt packages
  dnf:
    name:
      - salt-minion
    update_cache: true

- name: minion config
  template:
    src: minion
    dest: /etc/salt/minion

- name: start minion
  systemd:
    name: salt-minion
    state: started
    daemon_reload: true
    enabled: true